operate-first/common

github-config.yaml

feat: Test postsubmits

---

labels.yaml

feat: Add assign-to-oncall bot label

---

github-config.yaml

The PR contains:
- Addition of user Leihao Chen (username - Aaaaazzaa) to the members list and the team.contributors-core.members list.
Leihao Chen will be a contributor to the Curator project.

Adding user Leihao Chen (Aaaaazzaa)

---

github-config.yaml

Create new repo for tutorials as part of task https://github.com/operate-first/support/issues/326

feat: Add hitchhikers-guide repo

---

github-config.yaml

The PR contains:
-  Addition of user Leihao Chen (username - leihchen) to the member's list and the team.contributors-core.members list.
Leihao Chen will be a contributor to the Curator project.

Added LeihaoChen to the developer list

---

github-config.yaml

added my userId into the member list.

---

github-config.yaml

This is to add myself to the org, so that I can get issues assigned.
See https://github.com/operate-first/SRE/issues/389
Thanks!

Add Pep to the operate-first org

---

github-config.yaml

Team DevSecOps to look after the CI

Team DevSecOps to look after the CI

---

github-config.yaml

To track the odh team created by @durandom

Add odh team.

---

labels.yaml

Some labels I think we would benefit from.

Add labels for specific services, and additional areas.

---

labels.yaml

Add ocs label.

---

docs/add_gh_member_and_access.md
docs/add_repo.md
github-config.yaml

Also snuck in some minor clean up in the github-config.yaml file.

Add docs on managing users, teams, repos.

---

OWNERS
docs/add_gh_member_and_access.md

We'll pretend this didn't happen.

Clean up unnecessary text in member docs.

---

docs/add_gh_member_and_access.md
github-config.yaml

Related: https://github.com/operate-first/apps/pull/1356

Add two new gh members.

---

github-config.yaml

For: https://github.com/operate-first/sre-apprenticeship/pull/4#issuecomment-989106870

Add new members to org.

---

github-config.yaml

add sallyom gh

---

github-config.yaml

Looking forward to contributing to the training repository as a member of the Operate First community. :-)

Added my GitHub ID (stefwrite) to the list of org members

---

github-config.yaml

Add training github team.

---

github-config.yaml

Add Samuel to operate-first community

---

github-config.yaml

Resolve: https://github.com/operate-first/SRE/issues/452

Rename sre repo to operations.

---

OWNERS

schwesig to approvers:
schwesig to reviewers:
list of names sorted alphabetically

add schwesig to OWNERS

---

github-config.yaml

https://research.redhat.com/blog/research_project/ai-for-cloud-ops/ is the project page. This will happen on the operate first community platform.
We'll socialize the repo at this event: https://research.redhat.com/events/ai-for-cloud-ops/
cc @hpdempsey @akcoskun @zaoxing @gianlucasb @abyrne55 @mtoslalibu

AI for cloud operations

---

github-config.yaml

Add more odh members and make them odh-manifests admins.

---

.pre-commit-config.yaml
github-config.yaml

Give admin access to common repo to devsecops team

Give admin access to common repo to devsecops team

---

.prow.yaml

Fix label sync image binary
same as: https://github.com/open-services-group/community/pull/84

Fix label sync image binary

---

labels.yaml

Addresses: https://github.com/operate-first/operations/issues/462
/cc @HumairAK

Updating labels.yaml with a label for each cluster

---

github-config.yaml

add @roytman and @flora177 to operate first.
https://github.com/operate-first/community/pull/170

fybrik working group owners

---

github-config.yaml

Related to https://github.com/operate-first/sre/pull/6

Add sig-sre contributors

---

github-config.yaml

added a team to `github-config.yaml` to admin the new "Operate First In Action" repo.

added and admin team for opf in action repo

---

github-config.yaml

Adding SRE-U repo

---

github-config.yaml

Part of: https://github.com/operate-first/common/pull/91

Add sre-u repo and member.

---

github-config.yaml

Add user to seru team.

---

github-config.yaml

Part of: https://github.com/operate-first/common/pull/97
Forgot to add them to the org as well.

Add sreu member to org.

---

github-config.yaml

in preparation to launch the new website
https://github.com/operate-first/website-ng/issues/29

move_operate-first.github.io-to-old

---

github-config.yaml

Signed-off-by: Shreekar <sshreeka@redhat.com>

Add shreekarSS to operate-first community

---

github-config.yaml

In support of operate-first/sre#19

Add Dom Finn to org

---

github-config.yaml

This PR has the following changes:
* Add @AvRajath to the Curator team.

Adding AvRajath to the Curator GitHub team

---

github-config.yaml

fix: website maintainers invalid config

---

github-config.yaml

Change peribolos config to add a new repository
Part of [#2036](https://github.com/operate-first/apps/issues/2036)

chore(service-catalog): Add catalog repo

---

github-config.yaml

So they can be added to sre/OWNERS

Add two members of RH's SIG SRE team

---

github-config.yaml

needed to transfer data science repo to op1st

adding schwesig to admin

---

github-config.yaml
labels.md
labels.yaml

Part of: https://github.com/open-services-group/community/issues/231
~~**Do not merge, migration in progress**~~ Migration complete
/hold

feat: Relocate Probot repositories to Operate First

---

github-config.yaml

Add https://github.com/operate-first/robozome to org config after repo transfer.
/cc @larsks

feat: Add robozome repo

---

github-config.yaml

- Add Mike Knell (mknell@redhat) to sre members
- Add blog post author permissions

Add permissions for mknell@redhat (uffish)

---

github-config.yaml

Furthers: https://github.com/operate-first/operations/issues/487

Add OSC LF contributors.

---

github-config.yaml

Signed-off-by: mohammad-nassar10 <mohammad.nassar@ibm.com>

Adding a new github id to github-config.yaml.

---

OWNERS
github-config.yaml

Thank you for your service
- Removed the Members who have canceled operate-first membership.
Thank you for your service fridex and isabelizimm
- ordered the list alphabetically

:pray: Thank you for your service

---

github-config.yaml

feat: Add my name to triagers

---

github-config.yaml

/cc @cooktheryan
/cc @HumairAK

adding ryan cook to operate-first team for acm access

---

github-config.yaml

Signed-off-by: greg pereira <grpereir@redhat.com>
Thank you for you service.
PR to test if #101 is still an issue in effect or if it was a flake / has been resolved.

housekeeping, removing stale members to test prow permissions

---

github-config.yaml

Added myself as per the steps described in a reply to my issue operate-first/support#629

Added roastdeer to operate-first members

---

github-config.yaml

An action item of today's cluster ops sync. 
/cc @redmikhail 
/cc @HumairAK 
Signed-off-by: greg pereira <grpereir@redhat.com>

creating a utility-scripts repo

---

github-config.yaml

Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>

add djach7 and robotsail

---

labels.yaml

- Add `kind/plugin` for plugin development/installation
- Add `kind/system-definition` for issues that ask us to define a system from a real world deployment of services

feat: Add relevant labels to service-catalog

---

github-config.yaml

Part of: https://github.com/operate-first/apps/issues/2490

Add kepler team and edge demo repo.

---

github-config.yaml

closes https://github.com/operate-first/support/issues/1229

archive curator as req per issue

---

github-config.yaml

Cleanup after transfer
Resolves: https://github.com/operate-first/support/issues/1237
cc @goern

chore: remove curator-operator mention

---

.pre-commit-config.yaml
labels.md
labels.yaml

this implements https://github.com/operate-first/community/issues/239
- add sig/sre label
- updated pre-commit plugins

Create SIG-SRE label
