labels.yaml

- In https://github.com/thoth-station/thoth-application/pull/1611 we ended up with a specific set of changes for how the labels would appear
- In doing the final editing for that, I accidentally left these two labels that do not conform to the Prow scheme, nor are they what we intended to have happen from review.
- These labels shouldn't have been used anywhere already
Signed-off by: Karsten Wade <kwade@redhat.com>

Cruft entries from changes during review

---

github-config.yaml

Resolves: https://github.com/operate-first/common/issues/6
please review and leave on hold for a coordinated merge, I want to create the repo from a template - which has to be done manually right now.
/hold

feat: Add community-handbook repo

---

github-config.yaml

Let's join `contributors-core` and `contributors-web` teams, the distinction doesn't make much sense anymore.

feat: Join contributors teams

---

github-config.yaml

Breaks the automation runs, since the user no longer exists in GitHub
https://github.com/Aaaaazzaa
Fixes:
````
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:215","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure operate-first teams: failed to update contributors-core members: UpdateTeamMembership(4506398(contributors-core), aaaaazzaa, false) failed: status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#add-or-update-team-membership-for-a-user\"}","severity":"fatal","time":"2021-09-20T16:20:49+02:00"}
```

feat: Remove Aaaaazzaa user which no longer exists

---

github-config.yaml

Introduced twice in https://github.com/operate-first/common/pull/26 accidentally.

Remove duplicate user in contributors-core.

---

github-config.yaml

These users are still members. But they won't be needing triage permissions. Updated contributors-core team to reflect its purpose more accurately.

Convert core contrib to triage and cleanup triager team.

---

github-config.yaml

Related: https://github.com/thoth-station/support/issues/68
I think we should have one distinct from thoth that's specific to the operate-first org.

Add operate-first user.

---

github-config.yaml

- Closes issue #39 
- As per the discussion in issue #39, we are going to start with one repo and
have clearly named individual jupyter notebooks per course

Added new `training` repo

---

github-config.yaml

Readd a blank `sre` repo to be filled with general SRE–related materials.
For this repo to be created, I had to also remove the existing `sre` –> `operations` redirect, cause that caused a conflict. If need be, a "hey, you might be looking for /operations repo" note can be added near the top of README.md in the new `sre` repo.

New SRE repo

---

github-config.yaml

This PR has two changes:
- It adds @timflannagan to the Curator team
- It adds curator-operator to the custodians.repos list

Added timflannagan to the Curator team

---

github-config.yaml

This would allow me be assigned issues, create discussions,
and have CI run on my jobs. I'm working on the Open Source Services
aspect of Operate First.
As recommended by @[HumairAK](https://github.com/HumairAK)
https://github.com/operate-first/community/pull/154#issuecomment-1072489912

Add myself @stefwalter as a member of Operate First

---

github-config.yaml

fixes https://github.com/operate-first/common/issues/79
Started at and based on the Kick-Off Meeting 2022-03-16.
Creating a repo and team to start the IONOS HV with Operate First project.

creating the repo for IONOS OpenShift

---

docs/add_repo.md

Updated the docs to make it clear an additional step is required to "add_repo" to also add a team. I also added the `auto_init: true` as a recommendation, this should initialize the repo with an initial commit.

update docs to add team to new repo

---

labels.yaml

Adds labels for existing SIGs from the new charter, and a generic label so anything can be associated with SIGs overall/in-general.
Remake of #92 after rebasing.
All credit for this should go to @quaid, I am just hoping this fixes his git issue.

 Labels related to SIGs

---

github-config.yaml

- This is the home to the tooling, content, and processes/guidelines
for the blog.
- Blog tasks that happen in this repo:
- Writing
- Reviewing
- Publishing (tooling)
- Pull request blog posts
- Review via PR process
- Three teams:
- 'blog' is for all the people possible, to make the pool of writers
and reviewers as big as possible.
- 'blog-editorial' is for people who can approve PRs (so they get
published automatically) and can make changes to blog posts before
and after publication.
- 'blog-publishers' is for people who need to be able to manipulate
the repo so it can be hooked up for automatic publishing.
Two possible URLs for the blog are:
1. blog.operate-first.cloud
1. operate-first.cloud/blog
I prefer the sub-domain 'blog.operate-first.cloud', but I always like
to use subdomains. …

Creating a new `blog` repo and related teams

---

github-config.yaml

Adding @dastergon to the org in support of operate-first/sre#16, to address https://github.com/operate-first/sre/pull/16#issuecomment-1127725125

Add dastergon to the org

---

github-config.yaml

- This should fill out the roles properly now
- Note the cascading roles, hoping someone else can confirm I have
the cascade correct
`blog` members can write and review (`triage` the repo)
`blog-editorial` members can review and publish (`write` in the
repo)
`blog-publishers` members can rework the publishing platform
... but what is the difference between `maintainers` and
`members` and do I have it configured correctly?
- e.g. should maintainers also be in the members list?
Signed-off-by: Karsten Wade <kwade@redhat.com>

Forgot to create maintainers for the blog

---

github-config.yaml

- Currently just the one repo but could be other repos that drive
web properties
- This lets a group triage and maintain the website, currently the
Website Updates WG
- Adding myself as part of the group doing things in the WG and
having value from being able to approve and merge each other's
changes.
- One member does not aiui currently wish to be a maintainer for
anything new due to time constraints, so not having the auth
to publish means she won't be called to help there.
- My other reason for adding myself is my leadership role requires
me to be able to push changes to the website when I deem them
to be timely, including overriding normal gitops review and
manually merging myself.
Signed-off-by: Karsten Wade <kwade@redhat.com>

Creating group to maintain project websites

---

github-config.yaml

fix: sre-u has no main branch

---

github-config.yaml

Include jingyu for access to clusters

Include jingyu for access to clusters

---

OWNERS

With Approvers permissions I can expedite requests to join the operate-first team, and seeing as I am an admin in operate-first, this followed logically as somewhere I could pickup slack.
Signed-off-by: greg pereira <grpereir@redhat.com>

requesting approvers permissions in operate-first/common

---

github-config.yaml

Adds the apex team members to the operate-first org.

Add Apex Team Members

---

github-config.yaml

Add OS-Climate sostrades team as members of the operate-first organization to allow access to ArgoCD and ability to submit PR requests for managing relevant objects on OS-Climate clusters. This is replacement for PR https://github.com/operate-first/common/pull/161 , addressing all issues. Original PR could be closed

Add OS-Climate sostrades team users as members of the org

---

github-config.yaml

Proposing my promotion to org admin and general Operate First maintainer.
As part of the shift away from ET leadership in the project, we need a project lead who is tasked by their organization to do this work. At the moment that seems to be only me, therefore it is prudent to have me attain higher permission levels. In addition, I've been an active and impactful member of the community for almost two years, and have earned maintainer status by any rubric.

Adding 'quaid' as org owner/admin
